<b>Numpy Arrays</b>

In [6]:
import numpy as np
array1=np.array([1,2,3,4,5])
print(array1)

[1 2 3 4 5]


In [7]:
array1.shape

(5,)

In [8]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
a.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [9]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [10]:
#create a numpy array of zeroes
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [13]:
#create an identity matrix
i1=np.eye(4)
print(i1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
#create a numpy array with random values
rand1=np.random.random((3,4))
print(rand1)

[[0.75903983 0.5340066  0.49940789 0.64665549]
 [0.38135267 0.31468477 0.71022614 0.40993165]
 [0.12581562 0.37008471 0.90554267 0.66313776]]


In [15]:
#random values array within a specific range
rand2=np.random.randint(10,100,(3,5))
print(rand2)

[[96 65 86 65 61]
 [38 67 59 86 73]
 [14 22 19 55 60]]


In [16]:
#Array of evenly spaced values
arr=np.linspace(10,30,5)
print(arr)

[10. 15. 20. 25. 30.]


In [17]:
#Array of evenly spaced values
arr2=np.arange(10,30,5)
print(arr2)

[10 15 20 25]


In [18]:
#find array dimension
print(rand2.shape)

(3, 5)


In [19]:
#number of dimensions
print(rand2.ndim)

2


In [20]:
#Number of elements in an array
print(rand2.size)

15


In [21]:
#checking the datatype of the values in the array
print(rand2.dtype)

int32


In [22]:
#Math operations performed on np array
A=np.random.randint(0,10,(3,3))
B=np.random.randint(10,20,(3,3))
print(A)
print(B)
print(A+B) #print(np.add(A,B)

[[4 5 9]
 [5 9 6]
 [5 1 1]]
[[17 17 16]
 [19 11 13]
 [15 19 10]]
[[21 22 25]
 [24 20 19]
 [20 20 11]]


In [23]:
print(A-B)#print(np.sub(A,B)

[[-13 -12  -7]
 [-14  -2  -7]
 [-10 -18  -9]]


In [24]:
print(np.multiply(A,B)) #print(A*B)

[[ 68  85 144]
 [ 95  99  78]
 [ 75  19  10]]


In [25]:
print(np.divide(A,B)) #print(A/B)

[[0.23529412 0.29411765 0.5625    ]
 [0.26315789 0.81818182 0.46153846]
 [0.33333333 0.05263158 0.1       ]]


In [26]:
#Transpose
A1=np.random.randint(0,5,(2,3))
print(A1)
print(A1.shape)

[[1 2 1]
 [1 4 1]]
(2, 3)


In [27]:
trans=np.transpose(A1)
print(trans)
print(trans.shape)

[[1 1]
 [2 4]
 [1 1]]
(3, 2)


In [28]:
#Reshaping the array
B1=A1.reshape(3,2)
print(B1)

[[1 2]
 [1 1]
 [4 1]]
